vich_uploader:
    db_driver: orm

    mappings:
       file_upload:
           uri_prefix: /uploads/files
           upload_destination: '%kernel.project_dir%/public/uploads/files'
           namer: Vich\UploaderBundle\Naming\OrignameNamer
